### ISSUE TITLE
unable to install via pip

### ISSUE THREAD

**Issue by michaelrice** [dnaeon/pvc#1]
The install instructions say to `pip install pvc`  but it doesnt work..
## ○ → cat ~/.pip/pip.log 

/Users/errr/venvs/pvc/bin/pip run on Sun Apr 12 20:51:29 2015
Downloading/unpacking pvc
  Getting page https://pypi.python.org/simple/pvc/
  URLs to search for versions for pvc:
- https://pypi.python.org/simple/pvc/
  Analyzing links from page https://pypi.python.org/simple/pvc/
  Could not find any downloads that satisfy the requirement pvc
  Cleaning up...
  Removing temporary dir /Users/errr/venvs/pvc/build...
  No distributions at all found for pvc
  Exception information:
  Traceback (most recent call last):
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
  pip.exceptions.DistributionNotFound: No distributions at all found for pvc

**Comment by dnaeon** [comment]
For some reason the source distribution package didn't appear in PyPI, although trying to push the same version to PyPI said that the source archive was already there.

I had to bump the PVC version and push the new source package again and this time it showed up.

Thanks for reporting this, Michael!

``` bash
$ pip install pvc
Downloading/unpacking pvc
  Downloading pvc-0.1.1.tar.gz
  Running setup.py egg_info for package pvc

Downloading/unpacking humanize>=0.5.1 (from pvc)
  Downloading humanize-0.5.1.tar.gz
  Running setup.py egg_info for package humanize

Downloading/unpacking pythondialog>=3.2.1 (from pvc)
  Downloading pythondialog-3.2.2.tar.bz2 (1.4Mb): 1.4Mb downloaded
  Running setup.py egg_info for package pythondialog

    no previously-included directories found matching 'doc/screenshots/thumbs'
    no previously-included directories found matching 'doc/_build'
Downloading/unpacking pyvmomi>=5.5.0-2014.1.1 (from pvc)
  Downloading pyvmomi-5.5.0.2014.1.1.tar.gz (198Kb): 198Kb downloaded
  Running setup.py egg_info for package pyvmomi

Downloading/unpacking requests>=2.6.0 (from pvc)
  Downloading requests-2.6.0.tar.gz (450Kb): 450Kb downloaded
  Running setup.py egg_info for package requests

Downloading/unpacking vconnector>=0.3.7 (from pvc)
  Downloading vconnector-0.3.7.tar.gz
  Running setup.py egg_info for package vconnector

Downloading/unpacking six>=1.7.3 (from pyvmomi>=5.5.0-2014.1.1->pvc)
  Downloading six-1.9.0.tar.gz
  Running setup.py egg_info for package six

    no previously-included directories found matching 'documentation/_build'
Downloading/unpacking docopt>=0.6.2 (from vconnector>=0.3.7->pvc)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py egg_info for package docopt
Downloading/unpacking tabulate>=0.7.3 (from vconnector>=0.3.7->pvc)
  Downloading tabulate-0.7.5.tar.gz
  Running setup.py egg_info for package tabulate

Installing collected packages: pvc, humanize, pythondialog, pyvmomi, requests, vconnector, six, docopt, tabulate
  Running setup.py install for pvc
    changing mode of build/scripts-3.2/pvc-tui from 644 to 755

    changing mode of /home/mnikolov/venv/bin/pvc-tui to 755
  Running setup.py install for humanize

  Running setup.py install for pythondialog

    no previously-included directories found matching 'doc/screenshots/thumbs'
    no previously-included directories found matching 'doc/_build'
  Running setup.py install for pyvmomi

  Running setup.py install for requests

  Running setup.py install for vconnector
    changing mode of build/scripts-3.2/vconnector-cli from 644 to 755

    changing mode of /home/mnikolov/venv/bin/vconnector-cli to 755
  Running setup.py install for six

    no previously-included directories found matching 'documentation/_build'
  Running setup.py install for docopt

  Running setup.py install for tabulate

    Installing tabulate script to /home/mnikolov/venv/bin
Successfully installed pvc humanize pythondialog pyvmomi requests vconnector six docopt tabulate
Cleaning up...
```
