### ISSUE TITLE
Variable Flags for vnc, vmware, other external applications

### ISSUE THREAD

**Issue by sigkill** [dnaeon/pvc#10]
Wondering if it might be good to setup or have a script that can find some of these binaries automatically for people.

Also attempted to run vmware player on my mac via a docker host which worked with a lot of configuration tweaks vnc was a bit easier.

Either having a function to look for a .pvc_config or some type of file with the variables set in it might be helpful later on.

**Comment by dnaeon** [comment]
We can definitely do that. I will leave this as a low-priority task for now, though.

What issues did you have with VMware Player console?

On my GNU/Linux box I had now issues with it once VMware Player was installed.

**Comment by rapgro** [comment]
pyvmomi does not work with VMware player. As far as I know, you need ESXi with a proper license to get access for their special API handled with pyvmomi.
https://github.com/vmware/pyvmomi/blob/master/README.rst

Please correct me if I'm wrong in assumptions or misunderstand your issue or idea.

**Comment by rapgro** [comment]
see also #27

**Comment by rapgro** [comment]
Any news for this issue?

**Comment by dnaeon** [comment]
@rapgro Sorry, missed your last replies.

> pyvmomi does not work with VMware player. As far as I know, you need ESXi with a proper license to get access for their special API handled with pyvmomi.

I have been using it with VMware Player on Linux, and Fusion as well on macOS -- no problems there.

What issues did you specifically have?

**Comment by rapgro** [comment]
Fully understood about ESXi. We own licenses and looked for any available cli tools to access those VMs hosted on our ESXi servers. This issue is specifically about implementation to execute for graphical clients with proper parameters.

**Comment by dnaeon** [comment]
Are you using stand-alone esxi hosts, or are they managed by a vCenter? A big part of the APIs used by pvc are meant to be executed against a vCenter endpoint.

**Comment by rapgro** [comment]
yes, vCenter with a bunch of hosts

**Comment by dnaeon** [comment]
Sorry, got confused a bit. Can you explain what is currently not working in your setup?

You cannot launch a VM console using VMware Player or Fusion?

Can you also share what your setup is? OS where you run `pvc` on?

**Comment by rapgro** [comment]
no. This is a feature request to implement vnc and rdp.

**Comment by dnaeon** [comment]
VNC is support is present for quite some time.

You need to make sure that certain ports are open on the ESXi hosts in
order to use VNC console.

The other supported option is VMRC, and currently there's support for
macOS, Windows and Linux clients.

**Comment by rapgro** [comment]
What linux application is recommend for VMRC? Can you implement a RDP option with freerdp as well?

**Comment by dnaeon** [comment]
Nope, I cannot implement the underlying protocol used by MKS. That's why `pvc` uses the available tools provided by VMware.

**Comment by dnaeon** [comment]
Closing this one in favour of #24
