### ISSUE TITLE
SSL certificate verify failed error

### ISSUE THREAD

**Issue by dangtrinhnt** [dnaeon/pvc#20]
Hello,

After I entered username and password to login to my vCenter host, I got this error:

 [Errno 1] _ssl.c:510: error:14090086:SSL  
 routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed                                             

My vCenter's using a self-signed certificate.

Thanks,

Trinh

**Comment by dnaeon** [comment]
What is the version  of Python and  the PVC packages that you have installed?

**Comment by dangtrinhnt** [comment]
It's Python2.7.

**Comment by dnaeon** [comment]
What's the exact version?

What about PVC and it's dependencies?

**Comment by dangtrinhnt** [comment]
Hey,

Here is my venv:

humanize==0.5.1
pvc==0.2.0
python2-pythondialog==3.3.0
pyvmomi==6.0.0
requests==2.9.1
vconnector==0.4.6

**Comment by dnaeon** [comment]
Handling of self-signed certificates should already be handled for you by the latest `vconnector` release.

I've just tried on fresh virtual environments in Python 2.7.11 and Python 3.5.1 and a vCenter 6.0 host and cannot reproduce this issue.

What's the vSphere host version that you are connecting to?

**Comment by dangtrinhnt** [comment]
It's a vCenter server appliance v6 running on OpenSUSE.

Here is the screenshot:

![pvc](https://cloud.githubusercontent.com/assets/2570623/12568080/be316d52-c3f5-11e5-8128-5aadf9ee497a.png)

**Comment by dangtrinhnt** [comment]
BTW, I'm running on a Ubuntu 14.04 with python 2.7.6.

**Comment by dnaeon** [comment]
Hey @dangtrinhnt,

I'll get a test VM installed and test this, then get back to you with more details.

Thanks,
Marin

**Comment by dnaeon** [comment]
Hey @dangtrinhnt,

Please upgrade to Python 2.7.9 at least.

pyVmomi has dropped support for older Python versions, so you need at least Python 2.7.9.

https://github.com/vmware/pyvmomi/issues/329
https://github.com/vmware/pyvmomi/issues/306
https://github.com/vmware/vsphere-flocker-driver/issues/14
