### ISSUE TITLE
License validation

### ISSUE THREAD

**Issue by rapgro** [dnaeon/pvc#23]
Please provide a valid license file, e.g. setup.py mentions BSD but that's not sufficient for proper packaging in downstream distributions like Fedora.
Maybe use template from https://github.com/dnaeon/py-vpoller as it's BSD also.

**Comment by dnaeon** [comment]
Will do tomorrow.

**Comment by dnaeon** [comment]
Just published `v0.3.0` version in PyPI, which includes a LICENSE file.
