### ISSUE TITLE
Use vmrc on non-Darwin or search for vmrc, vmplayer from PATH

### ISSUE THREAD

**Issue by derekschrock** [dnaeon/pvc#24]
Linux has vmrc (https://my.vmware.com/en/web/vmware/details?downloadGroup=VMRC1004&productId=742)

Possible solutions:
 1. On non-Darwin search PATH for vmplayer, vmrc, etc.  use the first you find
 2. Switch `vmplayer` to `vmrc`

If 2 from my testing `vmrc` on Linux (I'd assume all platforms) support the `vmrc://...` scheme.  So it should be as simple as using `open` on Darwin and `vmrc` on non-Darwin then append the `vmrc://` URL to the list?  Otherwise, just change `vmplayer` to `vmrc`

**Comment by dnaeon** [comment]
Haven't tried on VMRC on Linux recently, so not sure whether `vmrc://` scheme is supported by VMRC. 

Can you test that, before I can switch that over to `vmrc` as the preferred method?

**Comment by derekschrock** [comment]
Testing with VMware Remote Console 11.2.0 build-16492666 on EL8 vmrc does accept a vmrc:// URL.

**Comment by rapgro** [comment]
Therefore, I suggested to implement RDP #27 or others #10

**Comment by dnaeon** [comment]
> Therefore, I suggested to implement RDP #27 or others #10

Have you seen my comments in #10  ?

@rapgro I also don't understand what's the issue with VMRC or VMPlayer? These are the standard vendor applications for accessing VMs.

**Comment by rapgro** [comment]
You're confusing. The point is obviously that vmrc is not working properly in Linux, does it? You stated it does not work. RDP can be a good alternative. For both, an external client tool is needed.

**Comment by dnaeon** [comment]
@rapgro 

> The point is obviously that vmrc is not working properly in Linux, does it?

What do you mean by that? It does work just fine and @derekschrock also confirmed that in a previous comment.

I've asked you a few times already about what issues you have with VMRC, but you haven't provided any details so far.

Anyways, here's a screenshot of a CentOS 8.x system, which uses `pvc` and `vmrc` for the console.

![Screenshot 2020-09-06 at 17 19 52](https://user-images.githubusercontent.com/242827/92328007-76e0dd00-f066-11ea-9d05-e6c79c614955.png)

I've also switched the VMRC console for GNU/Linux to use VMRC in https://github.com/dnaeon/pvc/commit/1b8b803d467d550fd21830d407f0e900b2b10363
