### ISSUE TITLE
RHEL8 / CentOS8

### ISSUE THREAD

**Issue by rapgro** [dnaeon/pvc#25]
FYI Package in repository.
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-4ff7a96fa8

```
yum install -y epel-release

yum install -y python3-pvc

/usr/bin/pvc-tui
```

**Comment by dnaeon** [comment]
Hey, that's nice! :)

Thanks for sharing!

Mind adding these instructions to the readme as well?

Thanks,
Marin

**Comment by rapgro** [comment]
Feel free to publish. But let's at least wait till the packages are landed in stable, currently still in testing/pending.

**Comment by rapgro** [comment]
Push to epel8 was successful.
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-4ff7a96fa8

But still an issue with epel7. Or I'd recommend users to EPEL8 (as addon repository for CentOS 8 or RHEL8).
https://bugzilla.redhat.com/show_bug.cgi?id=1800888
