### ISSUE TITLE
Password input

### ISSUE THREAD

**Issue by rapgro** [dnaeon/pvc#26]
How to enter the password? The input field in the dialog seems disabled.

**Comment by dnaeon** [comment]
It is not disabled,  it just doesn't echo back any input. Simply navigate to the field, either by using the arrows or ctrl-n. Then type in your password.

**Comment by rapgro** [comment]
Though, bad usability imho. Maybe add a short hint somewhere into the dialog to let users know.

**Comment by dnaeon** [comment]
If you think this can be made more user-friendly and output `*` instead please feel free to submit an MR, thanks!

**Comment by rapgro** [comment]
What's an MR? It's not nice to close without an available fix.
Stars aren't the best, agreed. But at least the input field should get a focus notification to let users know where to enter, the password can still be invisible as well in length.

**Comment by dnaeon** [comment]
Hey @rapgro ,

MR is a merge request, where you can propose a code change.

The password input widget is what it is, because that's how it is displayed when using `dialog`, which is what PVC uses to display stuff on the terminal.

PVC itself doesn't provide custom widget password styles, it simply uses what the dialog library provides.

**Comment by rapgro** [comment]
OK, thanks for explanation. Then I tend to delegate this as a feature request somehow to the `dialog` component, especially with the downstream package (Fedora).

**Comment by rapgro** [comment]
Done: https://bugzilla.redhat.com/show_bug.cgi?id=1815747

**Comment by rapgro** [comment]
From downstream bug:

> --- Comment #3 from Thomas E. Dickey <dickey@his.com> ---
> There's already a dialog option for this:
> 
>        --insecure
>               Makes the password widget friendlier but less secure, by echoing
>               asterisks for each character.
> 
> The password widget calls dlg_show_string, just like the form and mixedform
> widgets, and that function handles the --insecure option.

**Comment by rapgro** [comment]
Further, why's there the --no-mouse switch? This avoids better usability, at least when in a graphical terminal window.

**Comment by rapgro** [comment]
From downstream bug:

> --- Comment #3 from Thomas E. Dickey <x@y> ---
> There's already a dialog option for this:
> 
>        --insecure
>               Makes the password widget friendlier but less secure, by echoing
>               asterisks for each character.
> 
> The password widget calls dlg_show_string, just like the form and mixedform
> widgets, and that function handles the --insecure option.

**Comment by dnaeon** [comment]
@rapgro can you try out the `feat/passwordbox` branch and let me know how it looks?

https://github.com/dnaeon/pvc/tree/feat/passwordbox

I'd like to have some feedback first, before I merge this into `master`.

**Comment by rapgro** [comment]
LGTM but still waiting for my RHEL installation to can fully confirm.

**Comment by rapgro** [comment]
This works on my Fedora 32 system, thanks. The issue here can get closed.
