### ISSUE TITLE
RDP

### ISSUE THREAD

**Issue by rapgro** [dnaeon/pvc#27]
Feature request to implement an option to directly do RDP connection into a VM.
Besides VNC and VMRC as currently available.

Possible application to use could be to instrument [xrdp](http://xrdp.org/) as a console variant.

**Comment by rapgro** [comment]
[FreeRDP](http://www.freerdp.com/) seems to be recommended for Windows Server. Alternatively, there's [rdesktop](https://www.rdesktop.org/).

**Comment by dnaeon** [comment]
Closing this one in favour of #24
