### ISSUE TITLE
Executable not found: can't find the executable for the dialog-like program

### ISSUE THREAD

**Issue by michaelrice** [dnaeon/pvc#3]
Thanks for fixing #1 I am now able to `pip install -U pvc` but when I run `pvc-tui` I get the following:

Traceback (most recent call last):
  File "/Users/errr/venvs/pvc/bin/pvc-tui", line 39, in <module>
    main()
  File "/Users/errr/venvs/pvc/bin/pvc-tui", line 35, in main
    app = MainApp()
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pvc/core.py", line 50, in **init**
    self.dialog = Dialog(autowidgetsize=True)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/dialog.py", line 981, in **init**
    self._dialog_prg = _path_to_executable(dialog)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/dialog.py", line 467, in _path_to_executable
    "can't find the executable for the dialog-like "
dialog.ExecutableNotFound: Executable not found: can't find the executable for the dialog-like program

**Comment by dnaeon** [comment]
Hey Michael,

You need to have the `dialog(1)` executable present as well.

Executing `brew install dialog` should get it installed for you.

I will also make sure to have this documented.

**Comment by michaelrice** [comment]
That did fix it up. Thanks!

**Comment by Yuvi-gh** [comment]
how to fix this issue in mingw and cygwin.

**Comment by SorenKazam** [comment]
I know this post is a little old, but I have a doubt, I have Pythondialog installed and everything is working thanks to this post, but I installed it on my Ubuntu machine, if I go to Windows I will have to install it pythondialog too?

**Comment by dnaeon** [comment]
> I know this post is a little old, but I have a doubt, I have Pythondialog installed and everything is working thanks to this post, but I installed it on my Ubuntu machine, if I go to Windows I will have to install it pythondialog too?

Yep, you need to install these dependencies as well.
